[project]
name = "first-level-fighter"
version = "0.1.0"
description = "DND 5E first-level character sheet generator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "readchar>=4.2.1",
]
