import unittest
from first_level_fighter.write_sheet import write_sheet

class TestWriteSheet(unittest.TestCase):
    def test_write_sheet(self):
        character = ["Human",
                     "Jeff",
                     "True Neutral",
                     [10, 11, 12, 13, 14, 15],
                     [0, 0, 1, 1, 2, 2],
                     "Fighter", 
                     ["Fighting Style", "Second Wind"],
                     ["Medium","30", "Watch it Buddy", "Newsflash Pal"],
                     [10, 10, "Keg", "Bat"]]
        sheet = ["# Jeff",
                 "First-level Human Fighter",
                 "Alignment: True Neutral",
                 "",
                 "## Ability Scores & Modifiers",
                "STR: 10 (0)",
                "DEX: 11 (0)",
                "CON: 12 (1)",
                "INT: 13 (1)",
                "WIS: 14 (2)",
                "CHA: 15 (2)",
                "",
                "## Combat",
                "Initiative: 0",
                "Speed: 30 feet",
                "Size: Medium",
                "Hit Point Maximum: 11",
                "Hit Dice Size: 10",
                "",
                "## Skills",
                "Proficiency Bonus: +2",
                "Acrobatics (DEX): 0",
                "Animal handling (WIS): 2",
                "Arcana (INT): 1",
                "Athletics (STR): 0",
                "Deception (CHA): 2",
                "History (INT): 1",
                "Insight (WIS): 2",
                "Intimidation (CHA): 2",
                "Investigation (INT): 1",
                "Medicine (WIS): 2",
                "Nature (INT): 1",
                "Perception (WIS): 2",
                "Performance (CHA): 2",
                "Persuasion (CHA): 2",
                "Religion (INT): 1",
                "Sleight of Hand (DEX): 0",
                "Stealth (DEX): 0",
                "Survival (WIS): 2",
                "",
                "Passive Perception: 12",
                "",
                "## Class Abilities",
                "Fighting Style",
                "Second Wind",
                "",
                "## Human Abilities",
                "Watch it Buddy",
                "Newsflash Pal",
                "",
                "## Equipment",
                "Keg",
                "Bat"]
        result = write_sheet(character)
        self.assertEqual(result, sheet)