STR_INDEX = 0
DEX_INDEX = 1
CON_INDEX = 2
INT_INDEX = 3
WIS_INDEX = 4
CHA_INDEX = 5

DIE_1_INDEX = 0
DIE_2_INDEX = 1
DIE_3_INDEX = 2

ROLL_LOWER_BOUND = 1
ROLL_HIGHER_BOUND = 7
ALIGN_LOWER_BOUND = 0
ALIGN_HIGHER_BOUND = 3

PLUS_2 = 2
PLUS_1 = 1

SPECIES = 0
SPECIES_INDEX = 0
NAME_INDEX = 1
ALIGNMENT_INDEX = 2
STATS_INDEX = 3
MODS_INDEX = 4
CLASS_INDEX = 5
ABILITIES_INDEX = 6
SPECIES_ABILITIES_INDEX = 7
EQUIPMENT_INDEX = 8

HIT_DICE_INDEX = 0
HIT_POINTS_INDEX = 1

REMOVE_SPECIES_NAME = 1
REMOVE_CLASS_NAME = 1
REMOVE_LOWEST_DIE = 1
REMOVE_HP_INFO = 2